# Generated by Django 4.2.30 on 2026-09-09 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0022_productionbladdersetupmismatchevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0015_ordemservico_causa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrizFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_estavel', models.CharField(db_index=True, help_text='Código único de rastreabilidade (ex: MF-HOPPER-001)', max_length=50, unique=True, verbose_name='Identificador Estável / Código Interno')),
                ('numero_sequencial', models.PositiveIntegerField(help_text='Ex: 1 para 001, 2 para 002', verbose_name='Número Sequencial da Unidade')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo no Chão de Fábrica')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações do Exemplar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades_fisicas', to='production.productionmatrixcatalog', verbose_name='Modelo Canônico (Catálogo SCADA)')),
            ],
            options={
                'verbose_name': 'Matriz Física (Exemplar)',
                'verbose_name_plural': 'Matrizes Físicas (Exemplares)',
                'ordering': ['modelo__nome_exibicao', 'numero_sequencial'],
            },
        ),
        migrations.CreateModel(
            name='TipoServicoMatrizaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo de Serviço')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada')),
                ('exige_matriz_fisica', models.BooleanField(default=False, help_text='Se marcado, a solicitação não poderá ser finalizada sem a identificação do exemplar físico da matriz.', verbose_name='Exige Matriz Física?')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('ordem_exibicao', models.PositiveIntegerField(default=1, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Tipo de Serviço de Matrizaria',
                'verbose_name_plural': 'Tipos de Serviço de Matrizaria',
                'ordering': ['ordem_exibicao', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoServicoMatrizaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveIntegerField(db_index=True, default=1, verbose_name='Versão de Concorrência')),
                ('prensa_nome_snapshot', models.CharField(editable=False, max_length=120, verbose_name='Snapshot do Nome da Prensa na Abertura')),
                ('matriz_identificador_snapshot', models.CharField(blank=True, editable=False, max_length=150, null=True, verbose_name='Snapshot da Matriz Física Vinculada')),
                ('tipo_servico_nome_snapshot', models.CharField(editable=False, max_length=120, verbose_name='Snapshot do Tipo de Serviço')),
                ('exige_matriz_fisica_snapshot', models.BooleanField(default=False, editable=False, verbose_name='Snapshot da Regra de Exigência de Matriz')),
                ('descricao_solicitacao', models.TextField(verbose_name='Descrição da Necessidade / Problema')),
                ('prioridade', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente')], db_index=True, default='NORMAL', max_length=15, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EM_EXECUCAO', 'Em Execução'), ('AGUARDANDO_CONFERENCIA', 'Aguardando Conferência'), ('AGUARDANDO_RETRABALHO', 'Aguardando Retrabalho'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], db_index=True, default='SOLICITADO', max_length=30, verbose_name='Status Atual')),
                ('solicitado_por_nome', models.CharField(editable=False, max_length=150, verbose_name='Nome do Solicitante')),
                ('data_solicitacao', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data/Hora da Solicitação')),
                ('responsavel_atribuido_nome', models.CharField(blank=True, editable=False, max_length=150, null=True, verbose_name='Nome do Responsável Atual')),
                ('data_inicio_execucao', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Primeiro Início da Execução')),
                ('data_fim_execucao', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Último Término da Execução Técnica')),
                ('descricao_servico_executado', models.TextField(blank=True, null=True, verbose_name='Última Descrição do Serviço Executado')),
                ('conferido_por_nome', models.CharField(blank=True, editable=False, max_length=150, null=True, verbose_name='Nome do Conferente')),
                ('data_conferencia', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data/Hora da Conferência')),
                ('observacao_conferencia', models.TextField(blank=True, null=True, verbose_name='Observação da Conferência')),
                ('cancelado_por_nome', models.CharField(blank=True, editable=False, max_length=150, null=True, verbose_name='Nome de Quem Cancelou')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora do Cancelamento')),
                ('motivo_cancelamento', models.TextField(blank=True, null=True, verbose_name='Motivo do Cancelamento')),
                ('quantidade_retrabalhos', models.PositiveIntegerField(default=0, verbose_name='Quantidade de Ciclos de Retrabalho')),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_matrizaria_canceladas', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado Por')),
                ('conferido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_matrizaria_conferidas', to=settings.AUTH_USER_MODEL, verbose_name='Conferente / Responsável pelo Aceite')),
                ('finalizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_matrizaria_finalizadas', to=settings.AUTH_USER_MODEL, verbose_name='Último Executor que Finalizou')),
                ('iniciado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_matrizaria_iniciadas', to=settings.AUTH_USER_MODEL, verbose_name='Primeiro Executor que Iniciou')),
                ('matriz_fisica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_servico', to='matrizaria.matrizfisica', verbose_name='Matriz Física (Exemplar)')),
                ('prensa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_matrizaria', to='maintenance.machine', verbose_name='Prensa / Máquina')),
                ('responsavel_atribuido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_matrizaria_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Atual na Matrizaria')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_matrizaria_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('tipo_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='matrizaria.tiposervicomatrizaria', verbose_name='Tipo de Serviço')),
            ],
            options={
                'verbose_name': 'Solicitação de Serviço da Matrizaria',
                'verbose_name_plural': 'Solicitações de Serviço da Matrizaria',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoTransicaoServicoMatrizaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(max_length=30, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(max_length=30, verbose_name='Status Novo')),
                ('tipo_evento', models.CharField(choices=[('CRIACAO', 'Abertura da Solicitação'), ('INICIO', 'Início de Execução'), ('FINALIZACAO_EXECUCAO', 'Finalização Técnica'), ('CONFERENCIA_APROVADA', 'Aprovação na Conferência'), ('REJEICAO_RETRABALHO', 'Devolução para Retrabalho'), ('TRANSFERENCIA', 'Transferência de Responsável'), ('ALTERACAO_DADO', 'Ajuste Justificado de Informação'), ('CANCELAMENTO', 'Cancelamento')], max_length=40, verbose_name='Tipo de Evento')),
                ('usuario_nome_snapshot', models.CharField(max_length=150, verbose_name='Nome do Usuário Autor')),
                ('data_evento', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data/Hora do Evento')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação / Justificativa')),
                ('dados_modificados', models.TextField(blank=True, null=True, verbose_name='Resumo Estruturado de Dados Alterados')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_transicoes', to='matrizaria.solicitacaoservicomatrizaria', verbose_name='Solicitação Vinculada')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Autor da Ação')),
            ],
            options={
                'verbose_name': 'Histórico de Transição da Matrizaria',
                'verbose_name_plural': 'Histórico de Transições da Matrizaria',
                'ordering': ['data_evento', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CicloExecucaoMatrizaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ciclo', models.PositiveIntegerField(default=1, verbose_name='Número do Ciclo')),
                ('usuario_inicio_nome', models.CharField(max_length=150, verbose_name='Nome de Quem Iniciou o Ciclo')),
                ('data_inicio', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data/Hora de Início do Ciclo')),
                ('usuario_fim_nome', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome de Quem Encerrou o Ciclo')),
                ('data_fim', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data/Hora de Fim do Ciclo')),
                ('descricao_servico_executado', models.TextField(blank=True, null=True, verbose_name='Descrição do Serviço Executado Neste Ciclo')),
                ('forma_encerramento', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADO_TECNICO', 'Finalizado Técnico'), ('INTERROMPIDO_CANCELAMENTO', 'Interrompido por Cancelamento')], default='EM_ANDAMENTO', max_length=30, verbose_name='Forma de Encerramento')),
                ('matriz_fisica_snapshot', models.CharField(blank=True, max_length=150, null=True, verbose_name='Snapshot da Matriz no Ciclo')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciclos_execucao', to='matrizaria.solicitacaoservicomatrizaria', verbose_name='Solicitação Vinculada')),
                ('usuario_fim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciclos_matrizaria_finalizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Encerramento')),
                ('usuario_inicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciclos_matrizaria_iniciados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Início')),
            ],
            options={
                'verbose_name': 'Ciclo de Execução da Matrizaria',
                'verbose_name_plural': 'Ciclos de Execução da Matrizaria',
                'ordering': ['solicitacao', 'numero_ciclo'],
            },
        ),
        migrations.AddIndex(
            model_name='solicitacaoservicomatrizaria',
            index=models.Index(fields=['status', '-data_solicitacao'], name='matrizaria__status_91fc65_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitacaoservicomatrizaria',
            index=models.Index(fields=['prensa', '-data_solicitacao'], name='matrizaria__prensa__1829cd_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitacaoservicomatrizaria',
            index=models.Index(fields=['data_inicio_execucao', 'data_fim_execucao'], name='matrizaria__data_in_88a18f_idx'),
        ),
        migrations.AddConstraint(
            model_name='matrizfisica',
            constraint=models.UniqueConstraint(fields=('modelo', 'numero_sequencial'), name='uniq_matriz_fisica_modelo_seq'),
        ),
        migrations.AddConstraint(
            model_name='cicloexecucaomatrizaria',
            constraint=models.UniqueConstraint(fields=('solicitacao', 'numero_ciclo'), name='uniq_ciclo_solicitacao_numero'),
        ),
    ]
