# Generated by Django 4.2.30 on 2026-09-10 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matrizaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteImportacaoMatrizFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao_lote', models.CharField(max_length=100, unique=True, verbose_name='Identificação do Lote')),
                ('arquivo_nome', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('arquivo_hash', models.CharField(db_index=True, max_length=64, verbose_name='Hash SHA-256 do Arquivo')),
                ('responsavel', models.CharField(max_length=150, verbose_name='Responsável pela Execução')),
                ('data_importacao', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data/Hora da Execução')),
                ('simulacao', models.BooleanField(default=True, verbose_name='Foi Simulação (Dry-Run)?')),
                ('quantidade_linhas_lidas', models.PositiveIntegerField(default=0, verbose_name='Linhas Lidas')),
                ('quantidade_unidades_criadas', models.PositiveIntegerField(default=0, verbose_name='Unidades Criadas')),
                ('quantidade_unidades_preservadas', models.PositiveIntegerField(default=0, verbose_name='Unidades Preservadas')),
                ('status', models.CharField(default='SUCESSO', max_length=30, verbose_name='Status da Carga')),
                ('linhas_origem_json', models.TextField(blank=True, null=True, verbose_name='Linhas de Origem (JSON)')),
                ('ids_criados_json', models.TextField(blank=True, null=True, verbose_name='IDs Criados (JSON)')),
                ('relatorio_execucao', models.TextField(blank=True, null=True, verbose_name='Relatório Textual da Execução')),
            ],
            options={
                'verbose_name': 'Lote de Importação de Matrizes Físicas',
                'verbose_name_plural': 'Lotes de Importação de Matrizes Físicas',
                'ordering': ['-data_importacao'],
            },
        ),
        migrations.AddField(
            model_name='matrizfisica',
            name='chave_unidade_origem',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Chave da Unidade na Prévia (ex: P1-01-U01)'),
        ),
        migrations.AddField(
            model_name='matrizfisica',
            name='linha_origem',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID da Linha de Origem na Planilha'),
        ),
        migrations.AddField(
            model_name='matrizfisica',
            name='lote_importacao',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Identificação do Lote de Importação'),
        ),
        migrations.AddField(
            model_name='matrizfisica',
            name='numero_fisico_confirmado',
            field=models.CharField(blank=True, db_index=True, help_text='Número efetivamente observado e conferido gravado na matriz física (opcional).', max_length=50, null=True, verbose_name='Número Físico Confirmado (Gravado na Peça)'),
        ),
        migrations.AddField(
            model_name='matrizfisica',
            name='observacao_identificacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação da Identificação Física'),
        ),
        migrations.AddField(
            model_name='matrizfisica',
            name='origem_cadastro',
            field=models.CharField(db_index=True, default='MANUAL', max_length=50, verbose_name='Origem do Cadastro'),
        ),
        migrations.AddField(
            model_name='matrizfisica',
            name='possui_dote',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NAO_INFORMADO', 'Não informado')], db_index=True, default='NAO_INFORMADO', help_text='Indica se o exemplar físico possui rebaixo/área para gravação de número físico.', max_length=15, verbose_name='Possui Dote para Numeração'),
        ),
        migrations.AddField(
            model_name='matrizfisica',
            name='situacao_identificacao',
            field=models.CharField(choices=[('PENDENTE', 'Identificação Física Pendente / A Conferir'), ('CONFIRMADA', 'Identificação Física Confirmada')], db_index=True, default='PENDENTE', help_text='Define se o número e o exemplar físico já foram verificados em campo.', max_length=20, verbose_name='Situação da Identificação Física'),
        ),
    ]
