# Generated by Django 4.2.30 on 2026-09-17 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_ordemservico_causa_and_more'),
        ('matrizaria', '0002_loteimportacaomatrizfisica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoservicomatrizaria',
            name='destino',
            field=models.CharField(choices=[('MAQUINA', 'Prensa / Máquina'), ('MATRIZARIA', 'Matrizaria — Serviço interno / Sem máquina')], db_index=True, default='MAQUINA', max_length=20, verbose_name='Destino do Atendimento'),
        ),
        migrations.AlterField(
            model_name='solicitacaoservicomatrizaria',
            name='prensa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_matrizaria', to='maintenance.machine', verbose_name='Prensa / Máquina'),
        ),
    ]
