# Generated by Django 4.2.30 on 2026-07-29 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0011_whatsappgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionGlobalAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Alarme')),
                ('chave', models.CharField(help_text='Identificador único no sistema (ex: alarme_ar, alarme_vapor, alarme_vacuo).', max_length=50, unique=True, verbose_name='Chave Única')),
                ('xid', models.CharField(blank=True, max_length=100, null=True, verbose_name='XID no Scada-LTS')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Alarme Global',
                'verbose_name_plural': 'Alarmes Globais',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ProductionGlobalParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Parâmetro')),
                ('chave', models.CharField(help_text='Identificador único no sistema (ex: pressao_vacuo, vapor_1_7, pressao_ar).', max_length=50, unique=True, verbose_name='Chave Única')),
                ('xid', models.CharField(blank=True, max_length=100, null=True, verbose_name='XID no Scada-LTS')),
                ('unidade', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidade de Medida (ex: bar, mmHg)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Parâmetro Global',
                'verbose_name_plural': 'Parâmetros Globais',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ProductionMachineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_exibicao', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('stale_limit_seconds', models.PositiveIntegerField(default=120, help_text='Tempo máximo em segundos sem atualização do Scada antes de considerar dado desatualizado.', verbose_name='Limite para Dado Desatualizado (segundos)')),
                ('produzindo_value', models.CharField(default='1', help_text="Valor do XID de status que indica que a máquina está produzindo (ex: '1' ou 'true').", max_length=50, verbose_name='Valor Bruto que Indica Produzindo')),
                ('xid_status_prensa', models.CharField(blank=True, max_length=100, null=True, verbose_name='XID Status da Prensa (Produzindo/Parada)')),
                ('xid_abertura', models.CharField(blank=True, max_length=100, null=True, verbose_name='XID Sinal de Abertura')),
                ('xid_motivo_parada_geral', models.CharField(blank=True, max_length=100, null=True, verbose_name='XID Motivo de Parada Geral')),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_config', to='maintenance.machine', verbose_name='Máquina')),
            ],
            options={
                'verbose_name': 'Configuração de Máquina (Produção)',
                'verbose_name_plural': 'Configurações de Máquinas (Produção)',
                'ordering': ['ordem_exibicao', 'machine__nome'],
            },
        ),
        migrations.CreateModel(
            name='ProductionCavityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Cavidade 1, Cavidade A, Esquerda, etc.', max_length=50, verbose_name='Nome da Cavidade')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem de Exibição')),
                ('xid_producao', models.CharField(blank=True, max_length=100, null=True, verbose_name='XID Produção Atual')),
                ('xid_meta', models.CharField(blank=True, max_length=100, null=True, verbose_name='XID Meta de Produção')),
                ('xid_motivo_parada', models.CharField(blank=True, max_length=100, null=True, verbose_name='XID Motivo de Parada da Cavidade')),
                ('machine_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cavities', to='production.productionmachineconfig', verbose_name='Configuração da Máquina')),
            ],
            options={
                'verbose_name': 'Configuração de Cavidade',
                'verbose_name_plural': 'Configurações de Cavidades',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
