# Generated by Django 4.2.30 on 2026-07-30 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionmachineconfig',
            name='stale_limit_seconds',
            field=models.PositiveIntegerField(default=120, help_text='Tempo máximo em segundos sem atualização do Scada antes de considerar dado desatualizado.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Limite para Dado Desatualizado (segundos)'),
        ),
        migrations.AddConstraint(
            model_name='productioncavityconfig',
            constraint=models.UniqueConstraint(fields=('machine_config', 'nome'), name='uniq_prod_cavity_machine_nome'),
        ),
        migrations.AddConstraint(
            model_name='productioncavityconfig',
            constraint=models.UniqueConstraint(fields=('machine_config', 'ordem'), name='uniq_prod_cavity_machine_ordem'),
        ),
        migrations.AddConstraint(
            model_name='productionmachineconfig',
            constraint=models.CheckConstraint(check=models.Q(('stale_limit_seconds__gte', 1)), name='chk_prod_machine_stale_limit_gte_1'),
        ),
    ]
