# Generated by Django 4.2.30 on 2026-07-30 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_productionmachineconfig_stale_limit_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScadaDataPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('xid', models.CharField(max_length=50, unique=True)),
                ('data_source_id', models.IntegerField(db_column='dataSourceId')),
                ('point_name', models.CharField(blank=True, db_column='pointName', max_length=250, null=True)),
                ('plc_alarm_level', models.IntegerField(blank=True, db_column='plcAlarmLevel', null=True)),
            ],
            options={
                'verbose_name': 'Scada Data Point',
                'verbose_name_plural': 'Scada Data Points',
                'db_table': 'datapoints',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScadaPointValue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_type', models.IntegerField(db_column='dataType')),
                ('point_value', models.FloatField(blank=True, db_column='pointValue', null=True)),
                ('ts', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Scada Point Value',
                'verbose_name_plural': 'Scada Point Values',
                'db_table': 'pointvalues',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScadaPointValueAnnotation',
            fields=[
                ('point_value', models.OneToOneField(db_column='pointValueId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='annotation', serialize=False, to='production.scadapointvalue')),
                ('text_point_value_short', models.CharField(blank=True, db_column='textPointValueShort', max_length=128, null=True)),
                ('text_point_value_long', models.TextField(blank=True, db_column='textPointValueLong', null=True)),
            ],
            options={
                'verbose_name': 'Scada Point Value Annotation',
                'verbose_name_plural': 'Scada Point Value Annotations',
                'db_table': 'pointvalueannotations',
                'managed': False,
            },
        ),
    ]
