# Generated by Django 4.2.30 on 2026-07-30 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_scadadatapoint_scadapointvalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionMachineState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_atual', models.CharField(default='SEM_COMUNICACAO', max_length=30, verbose_name='Estado Atual')),
                ('inicio_estado_atual', models.DateTimeField(blank=True, null=True, verbose_name='Início do Estado Atual')),
                ('ultima_leitura_scada', models.DateTimeField(blank=True, null=True, verbose_name='Última Leitura Scada')),
                ('ultimo_timestamp_scada', models.BigIntegerField(blank=True, null=True, verbose_name='Último Timestamp Scada (ms)')),
                ('ultimo_valor_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Último Valor Bruto de Status')),
                ('motivo_atual', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo Atual')),
                ('sem_comunicacao', models.BooleanField(default=False, verbose_name='Sem Comunicação')),
                ('dado_desatualizado', models.BooleanField(default=False, verbose_name='Dado Desatualizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('machine_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='production.productionmachineconfig', verbose_name='Configuração da Máquina')),
            ],
            options={
                'verbose_name': 'Estado Atual da Máquina',
                'verbose_name_plural': 'Estados Atuais das Máquinas',
            },
        ),
        migrations.CreateModel(
            name='ProductionDowntimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='Início da Parada')),
                ('fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim da Parada')),
                ('duracao_segundos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração (segundos)')),
                ('motivo_geral', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo Geral de Parada')),
                ('snapshot_valor_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Snapshot Valor Status')),
                ('timestamp_inicial_scada', models.BigIntegerField(blank=True, null=True, verbose_name='Timestamp Inicial Scada (ms)')),
                ('timestamp_final_scada', models.BigIntegerField(blank=True, null=True, verbose_name='Timestamp Final Scada (ms)')),
                ('origem', models.CharField(default='SCADA', max_length=50, verbose_name='Origem do Registro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('machine_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtime_events', to='production.productionmachineconfig', verbose_name='Configuração da Máquina')),
            ],
            options={
                'verbose_name': 'Evento de Parada de Produção',
                'verbose_name_plural': 'Eventos de Parada de Produção',
                'ordering': ['-inicio'],
            },
        ),
    ]
