# Generated by Django 4.2.30 on 2026-07-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_productionmachinestate_productiondowntimeevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioncavityconfig',
            name='meta_producao_manual',
            field=models.PositiveIntegerField(default=0, help_text='Meta de produção manual para a cavidade (usada como fonte no dashboard).', verbose_name='Meta Manual de Produção'),
        ),
        migrations.AddField(
            model_name='productioncavityconfig',
            name='valor_cavidade_produzindo',
            field=models.CharField(default='1', help_text="Valor do XID que indica que a cavidade está produzindo (ex: '1').", max_length=50, verbose_name='Valor Bruto Cavidade Produzindo'),
        ),
        migrations.AddField(
            model_name='productioncavityconfig',
            name='xid_lote_bladder',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='XID Lote do Bladder'),
        ),
        migrations.AddField(
            model_name='productioncavityconfig',
            name='xid_matriz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='XID Matriz'),
        ),
        migrations.AddField(
            model_name='productioncavityconfig',
            name='xid_produto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='XID Produto'),
        ),
        migrations.AddField(
            model_name='productioncavityconfig',
            name='xid_status_cavidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='XID Status da Cavidade'),
        ),
        migrations.AlterField(
            model_name='productioncavityconfig',
            name='xid_meta',
            field=models.CharField(blank=True, help_text='Reservado para integração futura. O dashboard utiliza meta_producao_manual.', max_length=100, null=True, verbose_name='XID Meta de Produção (Reservado Futuro)'),
        ),
    ]
