# Generated by Django 4.2.30 on 2026-07-31 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_dados_operacionais_cavidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productioncavityconfig',
            name='valor_cavidade_produzindo',
        ),
        migrations.RemoveField(
            model_name='productioncavityconfig',
            name='xid_status_cavidade',
        ),
    ]
