# Generated by Django 4.2.30 on 2026-07-31 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_remove_status_individual_cavidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionMachineStateInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PRODUZINDO', 'Produzindo'), ('PARADA', 'Parada'), ('SEM_COMUNICACAO', 'Sem comunicação')], max_length=30, verbose_name='Estado')),
                ('started_at', models.DateTimeField(verbose_name='Data/Hora Inicial')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Final')),
                ('status_raw_value', models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor Bruto de Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('machine_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_intervals', to='production.productionmachineconfig', verbose_name='Configuração da Máquina')),
            ],
            options={
                'verbose_name': 'Intervalo de Estado da Máquina',
                'verbose_name_plural': 'Intervalos de Estados das Máquinas',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['machine_config', 'started_at'], name='production__machine_304209_idx'), models.Index(fields=['state', 'started_at'], name='production__state_8b3553_idx'), models.Index(fields=['ended_at'], name='production__ended_a_3a660b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductionCavityMatrixHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_value', models.CharField(max_length=100, verbose_name='Valor da Matriz')),
                ('started_at', models.DateTimeField(verbose_name='Data/Hora Inicial')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Final')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cavity_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_history', to='production.productioncavityconfig', verbose_name='Configuração da Cavidade')),
            ],
            options={
                'verbose_name': 'Histórico de Matriz de Cavidade',
                'verbose_name_plural': 'Históricos de Matrizes de Cavidades',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['cavity_config', 'started_at'], name='production__cavity__23495e_idx'), models.Index(fields=['started_at'], name='production__started_dd0a52_idx'), models.Index(fields=['ended_at'], name='production__ended_a_f320d8_idx')],
            },
        ),
    ]
