# Generated by Django 4.2.30 on 2026-08-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_productionmachinestateinterval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: 1º Turno, Turno Manhã, etc.', max_length=50, verbose_name='Nome do Turno')),
                ('horario_inicial', models.TimeField(verbose_name='Horário Inicial')),
                ('horario_final', models.TimeField(verbose_name='Horário Final')),
                ('atravessa_meia_noite', models.BooleanField(default=False, help_text='Marcado automaticamente se o horário final for menor ou igual ao horário inicial.', verbose_name='Atravessa a Meia-Noite')),
                ('percentual_meta', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentual da meta diária alocado para este turno. A soma dos turnos ativos deve dar 100.00% (ou 0.00% para distribuição igual).', max_digits=5, verbose_name='Percentual de Distribuição da Meta (%)')),
                ('ordem_exibicao', models.PositiveIntegerField(default=1, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Turno de Produção',
                'verbose_name_plural': 'Turnos de Produção',
                'ordering': ['ordem_exibicao', 'horario_inicial'],
            },
        ),
    ]
