# Generated by Django 4.2.30 on 2026-08-04 14:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_productionshift'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCavityState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_atual', models.CharField(choices=[('NORMAL', 'Normal'), ('PARADA', 'Parada'), ('INDETERMINADO', 'Indeterminado')], default='NORMAL', max_length=50, verbose_name='Estado Atual')),
                ('inicio_estado_atual', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Início do Estado Atual')),
                ('ultimo_motivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Último Motivo Registrado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cavity_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='production.productioncavityconfig', verbose_name='Configuração da Cavidade')),
            ],
            options={
                'verbose_name': 'Estado Atual da Cavidade',
                'verbose_name_plural': 'Estados Atuais das Cavidades',
            },
        ),
        migrations.CreateModel(
            name='ProductionCavityDowntimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='Início da Parada')),
                ('fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim da Parada')),
                ('duracao_segundos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração (segundos)')),
                ('motivo_parada', models.CharField(max_length=255, verbose_name='Motivo da Parada')),
                ('snapshot_valor_motivo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Snapshot Valor do Motivo')),
                ('timestamp_inicial_scada', models.BigIntegerField(blank=True, null=True, verbose_name='Timestamp Inicial Scada (ms)')),
                ('timestamp_final_scada', models.BigIntegerField(blank=True, null=True, verbose_name='Timestamp Final Scada (ms)')),
                ('origem', models.CharField(default='SCADA', max_length=50, verbose_name='Origem do Registro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cavity_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtime_events', to='production.productioncavityconfig', verbose_name='Configuração da Cavidade')),
            ],
            options={
                'verbose_name': 'Evento de Parada por Cavidade',
                'verbose_name_plural': 'Eventos de Parada por Cavidade',
                'ordering': ['-inicio'],
                'indexes': [models.Index(fields=['cavity_config', 'inicio'], name='production__cavity__d2cc29_idx'), models.Index(fields=['cavity_config', 'fim'], name='production__cavity__22ad02_idx')],
            },
        ),
    ]
