# Generated by Django 4.2.30 on 2026-08-04 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_productioncavitystate_productioncavitydowntimeevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRateAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Produto')),
                ('matriz', models.CharField(blank=True, max_length=100, null=True, verbose_name='Matriz')),
                ('inicio_intervalo', models.DateTimeField(verbose_name='Início do Intervalo')),
                ('fim_intervalo', models.DateTimeField(verbose_name='Fim do Intervalo')),
                ('minutos_produzindo', models.PositiveIntegerField(verbose_name='Minutos Produzindo')),
                ('quantidade_produzida', models.PositiveIntegerField(verbose_name='Quantidade Produzida')),
                ('taxa_pneus_hora', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Taxa (Pneus/Hora)')),
                ('quantidade_amostras', models.PositiveIntegerField(default=1, verbose_name='Quantidade de Amostras')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('cavity_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_aggregates', to='production.productioncavityconfig', verbose_name='Configuração de Cavidade')),
            ],
            options={
                'verbose_name': 'Agregado de Taxa de Produção',
                'verbose_name_plural': 'Agregados de Taxa de Produção',
                'ordering': ['-inicio_intervalo'],
                'indexes': [models.Index(fields=['cavity_config', 'produto', 'matriz'], name='production__cavity__69a0d3_idx'), models.Index(fields=['inicio_intervalo'], name='production__inicio__d4d1ab_idx')],
            },
        ),
    ]
