# Generated by Django 4.2.30 on 2026-08-04 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_productionrateaggregate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionParameterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Parâmetro')),
                ('chave', models.CharField(max_length=50, verbose_name='Chave Única')),
                ('xid', models.CharField(max_length=50, verbose_name='XID Scada')),
                ('unidade', models.CharField(default='°C', max_length=20, verbose_name='Unidade de Medida')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem de Exibição')),
                ('limite_minimo', models.FloatField(blank=True, null=True, verbose_name='Limite Mínimo')),
                ('limite_maximo', models.FloatField(blank=True, null=True, verbose_name='Limite Máximo')),
                ('tolerancia_segundos', models.PositiveIntegerField(default=0, verbose_name='Tolerância (Segundos)')),
                ('histerese', models.FloatField(default=0.0, verbose_name='Histerese de Retorno')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('stale_limit_seconds', models.PositiveIntegerField(default=120, verbose_name='Limite Stale (Segundos)')),
                ('cavity_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_configs', to='production.productioncavityconfig', verbose_name='Cavidade')),
                ('machine_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_configs', to='production.productionmachineconfig', verbose_name='Prensa / Máquina')),
            ],
            options={
                'verbose_name': 'Configuração de Parâmetro de Processo',
                'verbose_name_plural': 'Configurações de Parâmetros de Processo',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ProductionParameterAnomalyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='Início da Anomalia')),
                ('inicio_fora_faixa', models.DateTimeField(blank=True, null=True, verbose_name='Início Fora da Faixa')),
                ('fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim da Anomalia')),
                ('duracao_segundos', models.PositiveIntegerField(default=0, verbose_name='Duração (Segundos)')),
                ('menor_valor', models.FloatField(verbose_name='Menor Valor Registrado')),
                ('maior_valor', models.FloatField(verbose_name='Maior Valor Registrado')),
                ('ultimo_valor', models.FloatField(verbose_name='Último Valor Registrado')),
                ('tipo_limite', models.CharField(choices=[('MINIMO', 'Mínimo Violado'), ('MAXIMO', 'Máximo Violado')], max_length=10, verbose_name='Tipo de Limite')),
                ('produto_snapshot', models.CharField(blank=True, max_length=100, null=True, verbose_name='Produto (Snapshot)')),
                ('matriz_snapshot', models.CharField(blank=True, max_length=100, null=True, verbose_name='Matriz (Snapshot)')),
                ('lote_snapshot', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lote (Snapshot)')),
                ('cavity_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_events', to='production.productioncavityconfig', verbose_name='Cavidade')),
                ('downtime_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomaly_events', to='production.productiondowntimeevent', verbose_name='Evento de Parada Relacionado')),
                ('machine_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_events', to='production.productionmachineconfig', verbose_name='Máquina')),
                ('parameter_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_events', to='production.productionparameterconfig', verbose_name='Parâmetro')),
            ],
            options={
                'verbose_name': 'Evento de Anomalia de Parâmetro',
                'verbose_name_plural': 'Eventos de Anomalias de Parâmetros',
                'ordering': ['-inicio'],
                'indexes': [models.Index(fields=['parameter_config', 'inicio'], name='production__paramet_155ee5_idx'), models.Index(fields=['parameter_config', 'fim'], name='production__paramet_dc6a7d_idx')],
            },
        ),
    ]
