# Generated by Django 4.2.30 on 2026-08-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_productionparameterconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncavityconfig',
            name='meta_producao_manual',
            field=models.PositiveIntegerField(default=0, help_text='Meta diária de produção cadastrada manualmente pelo PCP / Líder de Produção.', verbose_name='Meta Manual de Produção'),
        ),
        migrations.AlterField(
            model_name='productioncavityconfig',
            name='xid_meta',
            field=models.CharField(blank=True, help_text='Código XID no Scada que fornece o limite de vida produtiva do ciclo do bladder.', max_length=100, null=True, verbose_name='XID Limite de Produção do Bladder (Scada)'),
        ),
    ]
