# Generated by Django 4.2.30 on 2026-08-04 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_separacao_limite_bladder_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionShiftAccumulated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data do Turno')),
                ('matriz', models.CharField(blank=True, max_length=100, null=True, verbose_name='Última Matriz')),
                ('produto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Último Produto')),
                ('quantity_accumulated', models.PositiveIntegerField(default=0, verbose_name='Quantidade Acumulada no Turno')),
                ('last_scada_counter', models.PositiveIntegerField(default=0, verbose_name='Último Contador Lido do Scada')),
                ('last_scada_ts', models.BigIntegerField(blank=True, null=True, verbose_name='Último Timestamp Scada (ms)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cavity_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_accumulated', to='production.productioncavityconfig', verbose_name='Cavidade')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accumulated_records', to='production.productionshift', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Acúmulo de Produção no Turno',
                'verbose_name_plural': 'Acúmulos de Produção nos Turnos',
            },
        ),
        migrations.CreateModel(
            name='ProductionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriz', models.CharField(blank=True, max_length=100, null=True, verbose_name='Matriz')),
                ('produto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Produto')),
                ('lote_bladder', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lote do Bladder')),
                ('started_at', models.DateTimeField(verbose_name='Início do Ciclo')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fim do Ciclo')),
                ('initial_counter', models.PositiveIntegerField(default=0, verbose_name='Contador Inicial')),
                ('final_counter', models.PositiveIntegerField(blank=True, null=True, verbose_name='Contador Final')),
                ('quantity_produced', models.PositiveIntegerField(default=0, verbose_name='Quantidade Produzida no Ciclo')),
                ('close_reason', models.CharField(blank=True, choices=[('RESET_CONTADOR', 'Reset de Contador Scada'), ('TROCA_MATRIZ', 'Troca de Matriz'), ('TROCA_BLADDER', 'Troca de Bladder'), ('FIM_TURNO', 'Fechamento de Turno'), ('MANUAL', 'Encerramento Manual')], max_length=30, null=True, verbose_name='Motivo do Fechamento')),
                ('last_scada_ts', models.BigIntegerField(blank=True, null=True, verbose_name='Último Timestamp Scada (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cavity_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='production.productioncavityconfig', verbose_name='Cavidade')),
            ],
            options={
                'verbose_name': 'Ciclo de Produção da Cavidade',
                'verbose_name_plural': 'Ciclos de Produção de Cavidades',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='productionshiftaccumulated',
            constraint=models.UniqueConstraint(fields=('date', 'shift', 'cavity_config'), name='uniq_prod_shift_accumulated_date_shift_cavity'),
        ),
    ]
