# Generated by Django 4.2.30 on 2026-08-04 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0013_allocationprogressupdate'),
        ('production', '0013_productioncycle_productionshiftaccumulated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionMatrixCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código canônico da matriz (ex: M-1024, MAT-A1).', max_length=50, unique=True, verbose_name='Código da Matriz')),
                ('descricao', models.CharField(blank=True, help_text='Descrição detalhada ou especificações (ex: Matriz 175/70R14 Curing).', max_length=200, null=True, verbose_name='Descrição da Matriz')),
                ('produto', models.CharField(blank=True, help_text='Nome/Código padronizado do pneu/produto.', max_length=100, null=True, verbose_name='Produto Padronizado')),
                ('aliases_scada', models.TextField(blank=True, help_text='Variações de texto recebidas do Scada separadas por vírgula (ex: MATRIZ 1024, Matriz 1024, 1024).', null=True, verbose_name='Aliases no Scada')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catálogo de Matriz/Produto',
                'verbose_name_plural': 'Catálogo de Matrizes e Produtos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ProductionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da Meta')),
                ('matriz_codigo', models.CharField(blank=True, help_text='Código da matriz para vínculo da meta.', max_length=100, null=True, verbose_name='Código da Matriz')),
                ('produto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Produto')),
                ('planned_quantity', models.PositiveIntegerField(verbose_name='Quantidade Planejada (Meta)')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observação / Justificativa')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('CANCELADO', 'Cancelado'), ('CONCLUIDO', 'Concluído')], default='ATIVO', max_length=20, verbose_name='Status da Meta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_targets', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
                ('matrix_catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targets', to='production.productionmatrixcatalog', verbose_name='Matriz (Catálogo)')),
                ('predicted_cavity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_targets', to='production.productioncavityconfig', verbose_name='Cavidade Prevista')),
                ('predicted_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_targets', to='maintenance.machine', verbose_name='Máquina Prevista')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='production.productionshift', verbose_name='Turno')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_production_targets', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Meta de Produção Planejada',
                'verbose_name_plural': 'Metas de Produção Planejadas',
                'ordering': ['-date', 'shift__ordem_exibicao', 'matriz_codigo'],
            },
        ),
    ]
