# Generated by Django 4.2.30 on 2026-08-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_productionmatrixcatalog_productiontarget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionmatrixcatalog',
            options={'ordering': ['codigo_scada', 'codigo'], 'verbose_name': 'Catálogo de Matriz/Produto', 'verbose_name_plural': 'Catálogo de Matrizes e Produtos'},
        ),
        migrations.AlterModelOptions(
            name='productiontarget',
            options={'ordering': ['-date', 'shift__ordem_exibicao', 'priority', 'matriz_codigo'], 'verbose_name': 'Meta de Produção Planejada', 'verbose_name_plural': 'Metas de Produção Planejadas'},
        ),
        migrations.AddField(
            model_name='productionmatrixcatalog',
            name='codigo_scada',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Código inteiro único (1 a 43) enviado pelo SCADA.', null=True, unique=True, verbose_name='Código SCADA'),
        ),
        migrations.AddField(
            model_name='productionmatrixcatalog',
            name='nome_exibicao',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome para Exibição'),
        ),
        migrations.AddField(
            model_name='productionmatrixcatalog',
            name='nome_scada',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome no SCADA'),
        ),
        migrations.AddField(
            model_name='productiontarget',
            name='change_reason',
            field=models.TextField(blank=True, help_text='Justificativa registrada ao alterar meta com turno em andamento.', null=True, verbose_name='Motivo da Última Alteração'),
        ),
        migrations.AddField(
            model_name='productiontarget',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1, help_text='Ordem de prioridade no plano do turno (1 = Maior prioridade).', verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='productionmatrixcatalog',
            name='aliases_scada',
            field=models.TextField(blank=True, help_text='Variações de texto recebidas do Scada separadas por vírgula.', null=True, verbose_name='Aliases no Scada'),
        ),
        migrations.AlterField(
            model_name='productionmatrixcatalog',
            name='codigo',
            field=models.CharField(help_text='Código canônico da matriz (ex: 3, 37, M-1024).', max_length=50, unique=True, verbose_name='Código da Matriz'),
        ),
        migrations.AlterField(
            model_name='productionmatrixcatalog',
            name='descricao',
            field=models.CharField(blank=True, help_text='Descrição detalhada ou especificações.', max_length=200, null=True, verbose_name='Descrição da Matriz'),
        ),
        migrations.AlterField(
            model_name='productiontarget',
            name='status',
            field=models.CharField(choices=[('PLANEJADA', 'Planejada'), ('AGUARDANDO_INSTALACAO', 'Aguardando Instalação'), ('EM_PRODUCAO', 'Em Produção'), ('ATINGIDA', 'Atingida'), ('CONCLUIDA_PARCIAL', 'Concluída Parcial'), ('CANCELADA', 'Cancelada'), ('ATIVO', 'Ativo - Legado'), ('CONCLUIDO', 'Concluído - Legado')], default='PLANEJADA', max_length=30, verbose_name='Status da Meta'),
        ),
    ]
