# Generated by Django 4.2.30 on 2026-08-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_alter_productionmatrixcatalog_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productiondowntimeevent',
            index=models.Index(fields=['machine_config', 'inicio'], name='production__machine_a36744_idx'),
        ),
        migrations.AddIndex(
            model_name='productiondowntimeevent',
            index=models.Index(fields=['inicio'], name='production__inicio_772f4b_idx'),
        ),
        migrations.AddIndex(
            model_name='productiondowntimeevent',
            index=models.Index(fields=['fim'], name='production__fim_c2b694_idx'),
        ),
    ]
