# Generated by Django 4.2.30 on 2026-08-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_productiondowntimeevent_production__machine_a36744_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncavityconfig',
            name='xid_lote_bladder',
            field=models.CharField(blank=True, help_text='Segunda parte do lote completo. Exemplo: no lote 6154 - 161046, este XID fornece 161046.', max_length=100, null=True, verbose_name='XID Número do Lote do Bladder'),
        ),
        migrations.AlterField(
            model_name='productioncavityconfig',
            name='xid_matriz',
            field=models.CharField(blank=True, help_text='Código da matriz/produto atualmente instalado, traduzido pelo catálogo canônico do SCADA.', max_length=100, null=True, verbose_name='XID Matriz'),
        ),
        migrations.AlterField(
            model_name='productioncavityconfig',
            name='xid_produto',
            field=models.CharField(blank=True, help_text='Primeira parte do lote completo. Exemplo: no lote 6154 - 161046, este XID fornece 6154.', max_length=100, null=True, verbose_name='XID Prefixo do Lote do Bladder'),
        ),
    ]
