# Generated by Django 4.2.30 on 2026-08-13 16:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0018_seed_matrix_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_bladder', models.CharField(help_text='Ex: BLA001, BLA002, etc.', max_length=50, unique=True, verbose_name='Código do Bladder')),
                ('descricao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descrição / Especificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Código de Bladder',
                'verbose_name_plural': 'Códigos de Bladders',
                'ordering': ['codigo_bladder'],
            },
        ),
        migrations.CreateModel(
            name='ProductionMatrixSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.CharField(help_text='Ex: 90/90-18, 2.75-18, 24X8-12.', max_length=50, unique=True, verbose_name='Medida / Tamanho')),
                ('medida_normalizada', models.CharField(db_index=True, help_text='Formato padronizado sem espaços adicionais e com remoção de zeros desnecessários.', max_length=50, verbose_name='Medida Normalizada')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medida de Matriz',
                'verbose_name_plural': 'Medidas de Matrizes',
                'ordering': ['medida'],
            },
        ),
        migrations.CreateModel(
            name='ProductionPCPPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField(verbose_name='Data/Hora de Início')),
                ('quantidade_programada', models.PositiveIntegerField(verbose_name='Quantidade Programada (Meta Total)')),
                ('turno_opcao', models.CharField(choices=[('A', 'Turno A'), ('B', 'Turno B'), ('AMBOS', 'Ambos os Turnos (A + B)')], default='AMBOS', max_length=10, verbose_name='Turno(s) Autorizado(s)')),
                ('cavidades_disponiveis', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cavidades Disponíveis (Capacidade Paralela)')),
                ('tempo_producao_utilizado', models.PositiveIntegerField(verbose_name='Tempo de Produção Utilizado (s)')),
                ('intervalo_utilizado', models.PositiveIntegerField(default=90, verbose_name='Intervalo Operacional Utilizado (s)')),
                ('perda_lixo_pct_utilizada', models.DecimalField(decimal_places=2, default=0.5, max_digits=5, verbose_name='Percentual Lixo Utilizado (%)')),
                ('perda_ia_pct_utilizada', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Percentual IA Utilizado (%)')),
                ('lixo_estimado', models.PositiveIntegerField(default=0, verbose_name='Lixo Estimado (Pneus)')),
                ('ia_estimada', models.PositiveIntegerField(default=0, verbose_name='IA Estimada (Pneus)')),
                ('perda_total_estimada', models.PositiveIntegerField(default=0, verbose_name='Perda Total Estimada (Pneus)')),
                ('producao_boa_estimada', models.PositiveIntegerField(default=0, verbose_name='Produção Boa Estimada (Pneus)')),
                ('data_hora_fim_prevista', models.DateTimeField(verbose_name='Data/Hora Final Prevista')),
                ('status', models.CharField(choices=[('PLANEJADO', 'Planejado'), ('EM_PRODUCAO', 'Em Produção'), ('ATINGIDA', 'Atingida / Concluído'), ('CANCELADO', 'Cancelado')], default='PLANEJADO', max_length=20, verbose_name='Status da Programação')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bladder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pcp_plans', to='production.productionbladder', verbose_name='Bladder Compatível Selecionado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pcp_plans', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
            ],
            options={
                'verbose_name': 'Programação PCP',
                'verbose_name_plural': 'Programações PCP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionPCPSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=50, unique=True, verbose_name='Chave de Configuração')),
                ('valor', models.CharField(max_length=100, verbose_name='Valor')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Global PCP',
                'verbose_name_plural': 'Configurações Globais PCP',
            },
        ),
        migrations.AddField(
            model_name='productionmatrixcatalog',
            name='medida_str',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Medida Texto Bruto'),
        ),
        migrations.AddField(
            model_name='productionmatrixcatalog',
            name='tempo_producao_segundos',
            field=models.PositiveIntegerField(default=760, help_text='Tempo total por pneu sem incluir o intervalo operacional entre pneus.', verbose_name='Tempo de Produção (s)'),
        ),
        migrations.AddField(
            model_name='productionmatrixcatalog',
            name='tempo_vulcanizacao_segundos',
            field=models.PositiveIntegerField(default=600, help_text='Tempo da etapa física de cura no molde.', verbose_name='Tempo de Vulcanização (s)'),
        ),
        migrations.AddField(
            model_name='productionmatrixcatalog',
            name='variante_sc',
            field=models.BooleanField(default=False, verbose_name='Variante Sem Câmara (S/C)'),
        ),
        migrations.AlterField(
            model_name='productionmatrixcatalog',
            name='codigo',
            field=models.CharField(help_text='Código canônico da matriz (ex: 3, 37, 44).', max_length=50, unique=True, verbose_name='Código da Matriz'),
        ),
        migrations.AlterField(
            model_name='productionmatrixcatalog',
            name='codigo_scada',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Código inteiro único enviado pelo SCADA.', null=True, unique=True, verbose_name='Código SCADA'),
        ),
        migrations.CreateModel(
            name='ProductionPCPPlanShiftTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data do Turno')),
                ('data_hora_inicio_janela', models.DateTimeField(verbose_name='Início da Janela')),
                ('data_hora_fim_janela', models.DateTimeField(verbose_name='Fim da Janela')),
                ('meta_prevista', models.PositiveIntegerField(verbose_name='Meta Prevista para este Turno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pcp_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_targets', to='production.productionpcpplan', verbose_name='Plano PCP')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcp_shift_targets', to='production.productionshift', verbose_name='Turno')),
                ('target_legado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pcp_shift_breakdowns', to='production.productiontarget', verbose_name='Registro de Meta Legado')),
            ],
            options={
                'verbose_name': 'Meta de Turno PCP',
                'verbose_name_plural': 'Metas de Turnos PCP',
                'ordering': ['date', 'shift__ordem_exibicao'],
            },
        ),
        migrations.AddField(
            model_name='productionpcpplan',
            name='matriz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pcp_plans', to='production.productionmatrixcatalog', verbose_name='Matriz / Modelo'),
        ),
        migrations.AddField(
            model_name='productionpcpplan',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pcp_plans', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
        migrations.AddField(
            model_name='productionbladder',
            name='medidas',
            field=models.ManyToManyField(blank=True, related_name='bladders', to='production.productionmatrixsize', verbose_name='Medidas Compatíveis'),
        ),
        migrations.AddField(
            model_name='productionmatrixcatalog',
            name='medida_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matrices', to='production.productionmatrixsize', verbose_name='Medida (Tamanho)'),
        ),
    ]
