# Generated by Django 4.2.30 on 2026-08-14 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0019_productionbladder_productionmatrixsize_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPCPPlanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora da Ação')),
                ('action_type', models.CharField(choices=[('CRIACAO', 'Criação'), ('EDICAO', 'Edição'), ('CANCELAMENTO', 'Cancelamento'), ('EXCLUSAO', 'Exclusão')], max_length=30, verbose_name='Tipo de Ação')),
                ('quantity_before', models.IntegerField(blank=True, null=True, verbose_name='Qtd Anterior')),
                ('quantity_after', models.IntegerField(blank=True, null=True, verbose_name='Qtd Nova')),
                ('shift_choice_before', models.CharField(blank=True, max_length=20, null=True, verbose_name='Turno Anterior')),
                ('shift_choice_after', models.CharField(blank=True, max_length=20, null=True, verbose_name='Turno Novo')),
                ('cavities_before', models.IntegerField(blank=True, null=True, verbose_name='Cavidades Anterior')),
                ('cavities_after', models.IntegerField(blank=True, null=True, verbose_name='Cavidades Novas')),
                ('final_dt_before', models.DateTimeField(blank=True, null=True, verbose_name='Término Anterior')),
                ('final_dt_after', models.DateTimeField(blank=True, null=True, verbose_name='Término Novo')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Motivo / Observações')),
                ('pcp_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='production.productionpcpplan', verbose_name='Plano PCP')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pcp_plan_history_entries', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'db_table': 'production_pcp_plan_history',
                'verbose_name': 'Histórico de Programação PCP',
                'verbose_name_plural': 'Históricos de Programação PCP',
                'ordering': ['-created_at'],
            },
        ),
    ]
