# Generated by Django 4.2.30 on 2026-08-19 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_productionpcpplanhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioncavityconfig',
            name='xid_bla_real',
            field=models.CharField(blank=True, help_text='Código BLA do bladder lido do SCADA na cavidade.', max_length=100, null=True, verbose_name='XID BLA Real Instalado'),
        ),
        migrations.AddField(
            model_name='productioncavityconfig',
            name='xid_motivo_troca_bladder',
            field=models.CharField(blank=True, help_text='Código numérico (0 a 8) do motivo de troca do bladder.', max_length=100, null=True, verbose_name='XID Motivo da Troca do Bladder'),
        ),
        migrations.CreateModel(
            name='ProductionBladderUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name_snapshot', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prensa / Máquina (Snapshot)')),
                ('cavity_name_snapshot', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cavidade (Snapshot)')),
                ('codigo_bla_real', models.CharField(db_index=True, help_text='Código normalizado do BLA (ex: BLA003).', max_length=50, verbose_name='Código BLA Real')),
                ('raw_bla_value', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor Bruto do BLA Lido')),
                ('lote_prefixo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prefixo do Lote')),
                ('lote_numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Lote')),
                ('lote_completo_snapshot', models.CharField(db_index=True, max_length=100, verbose_name='Lote Completo (Snapshot)')),
                ('started_at', models.DateTimeField(db_index=True, verbose_name='Data/Hora de Início')),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data/Hora Final')),
                ('timestamp_scada_inicio', models.BigIntegerField(blank=True, null=True, verbose_name='Timestamp SCADA Início (ms)')),
                ('timestamp_scada_fim', models.BigIntegerField(blank=True, null=True, verbose_name='Timestamp SCADA Fim (ms)')),
                ('passadas_acumuladas', models.PositiveIntegerField(default=0, verbose_name='Passadas Acumuladas')),
                ('limite_vida_snapshot', models.PositiveIntegerField(blank=True, null=True, verbose_name='Limite de Vida (Snapshot)')),
                ('motivo_troca', models.IntegerField(choices=[(0, 'Nenhum / Não informado'), (1, 'Vazamento'), (2, 'Bladder estourou'), (3, 'Deformação no bladder'), (4, 'Troca de matriz'), (5, 'Problemas dimensionais'), (6, 'Contaminação'), (7, 'Desgaste natural'), (8, 'Outros')], default=0, verbose_name='Motivo da Troca')),
                ('motivo_troca_raw', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Bruto do Motivo')),
                ('status', models.CharField(choices=[('EM_USO', 'Em Uso'), ('FINALIZADO', 'Finalizado')], db_index=True, default='EM_USO', max_length=20, verbose_name='Status da Utilização')),
                ('last_scada_counter', models.PositiveIntegerField(default=0, verbose_name='Último Contador Lido')),
                ('last_scada_ts', models.BigIntegerField(blank=True, null=True, verbose_name='Último Timestamp Scada (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cavity_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bladder_usages', to='production.productioncavityconfig', verbose_name='Cavidade')),
            ],
            options={
                'verbose_name': 'Utilização de Bladder',
                'verbose_name_plural': 'Utilizações de Bladders',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['cavity_config', 'status'], name='production__cavity__4a6f19_idx'), models.Index(fields=['codigo_bla_real', 'lote_completo_snapshot'], name='production__codigo__7f3f0f_idx'), models.Index(fields=['started_at'], name='production__started_10d337_idx'), models.Index(fields=['ended_at'], name='production__ended_a_177d42_idx')],
            },
        ),
    ]
