# Generated by Django 4.2.30 on 2026-08-19 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0021_productioncavityconfig_xid_bla_real_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBladderSetupMismatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name_snapshot', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prensa / Máquina (Snapshot)')),
                ('cavity_name_snapshot', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cavidade (Snapshot)')),
                ('matriz_instalada_raw', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código da Matriz Lida')),
                ('matriz_nome_snapshot', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Matriz (Snapshot)')),
                ('codigo_bla_instalado', models.CharField(db_index=True, max_length=50, verbose_name='Código BLA Instalado')),
                ('lote_bladder_snapshot', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lote do Bladder (Snapshot)')),
                ('bladders_esperados_snapshot', models.CharField(max_length=200, verbose_name='BLAs Autorizados / Esperados (Snapshot)')),
                ('started_at', models.DateTimeField(db_index=True, verbose_name='Data/Hora de Início da Divergência')),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data/Hora de Resolução')),
                ('duracao_segundos', models.PositiveIntegerField(default=0, verbose_name='Duração da Divergência (s)')),
                ('passadas_produzidas_em_divergencia', models.PositiveIntegerField(default=0, verbose_name='Passadas Produzidas em Divergência')),
                ('status', models.CharField(choices=[('EM_ABERTO', 'Em Aberto'), ('FINALIZADO', 'Finalizado')], db_index=True, default='EM_ABERTO', max_length=20, verbose_name='Status do Evento')),
                ('resolvido_por', models.CharField(blank=True, default='SETUP_CORRIGIDO', max_length=50, null=True, verbose_name='Forma de Resolução')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cavity_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_mismatch_events', to='production.productioncavityconfig', verbose_name='Cavidade')),
            ],
            options={
                'verbose_name': 'Evento de Divergência de Setup de Bladder',
                'verbose_name_plural': 'Eventos de Divergência de Setup de Bladders',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['cavity_config', 'status'], name='production__cavity__f8a2a1_idx'), models.Index(fields=['codigo_bla_instalado', 'status'], name='production__codigo__1baa65_idx'), models.Index(fields=['started_at'], name='production__started_ee1b20_idx'), models.Index(fields=['ended_at'], name='production__ended_a_d78f25_idx')],
            },
        ),
    ]
