# Generated by Django 4.2.30 on 2026-09-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_ordemservico_causa_and_more'),
        ('production', '0022_productionbladdersetupmismatchevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAlertRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Destinatário')),
                ('telefone', models.CharField(help_text='Informe com DDD (ex: 31999999999 ou 5531999999999).', max_length=30, verbose_name='Número de WhatsApp')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Destinatário de Alerta WhatsApp',
                'verbose_name_plural': 'Destinatários de Alerta WhatsApp',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='productionglobalalarm',
            name='alerta_inicial_enviado',
            field=models.BooleanField(default=False, verbose_name='Alerta Inicial Enviado'),
        ),
        migrations.AddField(
            model_name='productionglobalalarm',
            name='delay_segundos',
            field=models.PositiveIntegerField(default=60, help_text='Tempo de permanência contínua fora da faixa antes de considerar alarme.', verbose_name='Delay antes do Alarme (segundos)'),
        ),
        migrations.AddField(
            model_name='productionglobalalarm',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Alarme'),
        ),
        migrations.AddField(
            model_name='productionglobalalarm',
            name='estado_atual',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('PENDENTE', 'Pendente'), ('ALARME_ATIVO', 'Alarme Ativo'), ('DESABILITADO', 'Desabilitado')], default='NORMAL', max_length=20, verbose_name='Estado Atual'),
        ),
        migrations.AddField(
            model_name='productionglobalalarm',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='alarmes_scada', to='maintenance.whatsappgroup', verbose_name='Grupos de WhatsApp'),
        ),
        migrations.AddField(
            model_name='productionglobalalarm',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AddField(
            model_name='productionglobalalarm',
            name='inicio_fora_faixa',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início Fora da Faixa'),
        ),
        migrations.AddField(
            model_name='productionglobalalarm',
            name='intervalo_repeticao_minutos',
            field=models.PositiveIntegerField(choices=[(1, '1 minuto'), (5, '5 minutos'), (10, '10 minutos'), (30, '30 minutos')], default=10, help_text='Intervalo mínimo entre notificações enquanto o valor continuar fora da faixa.', verbose_name='Repetir enquanto estiver em alarme'),
        ),
        migrations.AddField(
            model_name='productionglobalalarm',
            name='notificar_normalizacao',
            field=models.BooleanField(default=True, verbose_name='Notificar Retorno ao Normal'),
        ),
        migrations.AddField(
            model_name='productionglobalalarm',
            name='ultima_leitura_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora da Última Leitura'),
        ),
        migrations.AddField(
            model_name='productionglobalalarm',
            name='ultima_leitura_valor',
            field=models.FloatField(blank=True, null=True, verbose_name='Última Leitura Válida'),
        ),
        migrations.AddField(
            model_name='productionglobalalarm',
            name='ultima_normalizacao_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Normalização Em'),
        ),
        migrations.AddField(
            model_name='productionglobalalarm',
            name='ultimo_alerta_enviado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Alerta Enviado Em'),
        ),
        migrations.AddField(
            model_name='productionglobalalarm',
            name='unidade',
            field=models.CharField(blank=True, help_text='Ex: bar, °C, litros, %, etc.', max_length=20, null=True, verbose_name='Unidade de Medida'),
        ),
        migrations.AddField(
            model_name='productionglobalalarm',
            name='valor_maximo',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor Máximo Permitido'),
        ),
        migrations.AddField(
            model_name='productionglobalalarm',
            name='valor_minimo',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor Mínimo Permitido'),
        ),
        migrations.AddField(
            model_name='productionglobalalarm',
            name='destinatarios',
            field=models.ManyToManyField(blank=True, related_name='alarmes', to='production.whatsappalertrecipient', verbose_name='Destinatários Individuais'),
        ),
    ]
