"""
Django settings for maintenance_project project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carregar variáveis de ambiente do arquivo .env
load_dotenv(BASE_DIR / ".env")


def _get_env(primary_name, fallback_name=None, default=None):
    val = os.environ.get(primary_name)
    if val is not None and val.strip() != "":
        return val.strip()
    if fallback_name:
        val = os.environ.get(fallback_name)
        if val is not None and val.strip() != "":
            return val.strip()
    return default


def _parse_bool(val, default=False):
    if val is None:
        return default
    val_str = str(val).strip().lower()
    if val_str in ("true", "1", "yes", "on", "t"):
        return True
    if val_str in ("false", "0", "no", "off", "f"):
        return False
    return default


def _parse_list(val, default=None):
    if default is None:
        default = []
    if not val:
        return default
    return [item.strip() for item in str(val).split(",") if item.strip()]



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# Modo de depuração (DEBUG)
raw_debug = _get_env("DJANGO_DEBUG", "DEBUG", default="True")
DEBUG = _parse_bool(raw_debug, default=True)

# SECRET_KEY
raw_secret = _get_env("DJANGO_SECRET_KEY", "SECRET_KEY")
if not raw_secret:
    if DEBUG:
        SECRET_KEY = "django-insecure-m5=fgwb0=lmm(#!_2%*v!j-1v%du!y++6nhoplf1vfttbthz14"
    else:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY deve ser configurada explicitamente em ambiente de produção (DEBUG=False)."
        )
else:
    if not DEBUG and raw_secret.startswith("django-insecure-"):
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY em ambiente de produção não pode utilizar a chave insegura de desenvolvimento."
        )
    SECRET_KEY = raw_secret

# ALLOWED_HOSTS
raw_allowed_hosts = _get_env("DJANGO_ALLOWED_HOSTS", "ALLOWED_HOSTS")
if raw_allowed_hosts is not None:
    ALLOWED_HOSTS = _parse_list(raw_allowed_hosts)
else:
    ALLOWED_HOSTS = ["*"] if DEBUG else []

if not DEBUG:
    if not ALLOWED_HOSTS or ALLOWED_HOSTS == ["*"]:
        raise ImproperlyConfigured(
            "DJANGO_ALLOWED_HOSTS deve conter hosts válidos e explícitos em produção (DEBUG=False) e não pode ser '*'."
        )

# CSRF_TRUSTED_ORIGINS
raw_csrf = _get_env("DJANGO_CSRF_TRUSTED_ORIGINS", "CSRF_TRUSTED_ORIGINS")
CSRF_TRUSTED_ORIGINS = _parse_list(raw_csrf)

# ── Reverse Proxy & Cloudflare Tunnel Settings ────────────────────────────────
USE_X_FORWARDED_HOST = _parse_bool(_get_env("DJANGO_USE_X_FORWARDED_HOST", "USE_X_FORWARDED_HOST"), default=False)
trust_proxy_ssl = _parse_bool(_get_env("DJANGO_TRUST_PROXY_SSL_HEADER", "TRUST_PROXY_SSL_HEADER"), default=False)
if trust_proxy_ssl:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_SSL_REDIRECT = _parse_bool(_get_env("DJANGO_SECURE_SSL_REDIRECT", "SECURE_SSL_REDIRECT"), default=False)
SESSION_COOKIE_SECURE = _parse_bool(_get_env("DJANGO_SESSION_COOKIE_SECURE", "SESSION_COOKIE_SECURE"), default=False)
CSRF_COOKIE_SECURE = _parse_bool(_get_env("DJANGO_CSRF_COOKIE_SECURE", "CSRF_COOKIE_SECURE"), default=False)
SECURE_HSTS_SECONDS = int(_get_env("DJANGO_SECURE_HSTS_SECONDS", "SECURE_HSTS_SECONDS", default="0") or "0")
SECURE_HSTS_INCLUDE_SUBDOMAINS = _parse_bool(_get_env("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", "SECURE_HSTS_INCLUDE_SUBDOMAINS"), default=False)
SECURE_HSTS_PRELOAD = _parse_bool(_get_env("DJANGO_SECURE_HSTS_PRELOAD", "SECURE_HSTS_PRELOAD"), default=False)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "maintenance",
    "production",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "maintenance.middleware.SessionExpiryByProfileMiddleware",  # Expiração de sessão por perfil (após AuthenticationMiddleware)
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ── Controle de Sessão por Turno (Absolute Session Timeout) ──────────────────
SESSION_COOKIE_AGE = 14400              # 4 horas — tempo médio de turno de trabalho
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Expira também ao fechar o navegador
SESSION_SAVE_EVERY_REQUEST = False      # NÃO renovar a cada request (expiração absoluta)

ROOT_URLCONF = "maintenance_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "maintenance_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DB_ENGINE = os.environ.get("DATABASE_ENGINE", "django.db.backends.sqlite3")

if DB_ENGINE == "django.db.backends.sqlite3":
    default_db_config = {
        "ENGINE": DB_ENGINE,
        "NAME": BASE_DIR / os.environ.get("DATABASE_NAME", "db.sqlite3"),
    }
else:
    default_db_config = {
        "ENGINE": DB_ENGINE,
        "NAME": os.environ.get("DATABASE_NAME", "painel_manutencao"),
        "USER": os.environ.get("DATABASE_USER", ""),
        "PASSWORD": os.environ.get("DATABASE_PASSWORD", ""),
        "HOST": os.environ.get("DATABASE_HOST", "127.0.0.1"),
        "PORT": os.environ.get("DATABASE_PORT", "3306"),
    }

DATABASES = {
    "default": default_db_config,
    "scada": {
        "ENGINE": os.environ.get("SCADA_DB_ENGINE", "django.db.backends.mysql"),
        "NAME": os.environ.get("SCADA_DB_NAME", "scadalts"),
        "USER": os.environ.get("SCADA_DB_USER", "scada_monitor_ro"),
        "PASSWORD": os.environ.get("SCADA_DB_PASSWORD", "SENHA_FORTE_LEITURA"),
        "HOST": os.environ.get("SCADA_DB_HOST", "127.0.0.1"),
        "PORT": os.environ.get("SCADA_DB_PORT", "3306"),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}

import sys
if "test" in sys.argv:
    DATABASES["scada"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db_test_scada.sqlite3",
    }

DATABASE_ROUTERS = ["production.routers.ScadaRouter"]


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = os.environ.get("LANGUAGE_CODE", "pt-br")

TIME_ZONE = os.environ.get("TIME_ZONE", "America/Sao_Paulo")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

# Media files (uploaded photos, etc.)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication redirects
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home_redirect"
LOGOUT_REDIRECT_URL = "login"

# Microserviços Auxiliares
WHATSAPP_SERVICE_URL = os.environ.get("WHATSAPP_SERVICE_URL", "http://localhost:3000/send")

