# Generated by Django 4.2.30 on 2026-09-29 14:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0015_ordemservico_causa_and_more'),
        ('production', '0023_whatsappalertrecipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApontamentoTurnoBladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(choices=[('TURMA_A', 'Turma A'), ('TURMA_B', 'Turma B'), ('APOIO', 'Apoio Operacional')], max_length=10, verbose_name='Turma')),
                ('data_turno', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data do Turno')),
                ('data_hora_inicio', models.DateTimeField(verbose_name='Início da Atividade')),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True, verbose_name='Término da Atividade')),
                ('quantidade_realizada', models.PositiveIntegerField(default=0, verbose_name='Quantidade Produzida')),
                ('situacao', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('PARCIAL', 'Execução Parcial'), ('INTERROMPIDA', 'Interrompida com Problema')], default='EM_ANDAMENTO', max_length=20, verbose_name='Situação')),
                ('motivo_desvio', models.TextField(blank=True, null=True, verbose_name='Motivo do Desvio / Ocorrência')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações do Operador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apontamentos_bladder', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Apontamento Operacional de Bladder',
                'verbose_name_plural': 'Apontamentos Operacionais de Bladder',
                'ordering': ['-data_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoEscalaBladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data de Referência')),
                ('turma_referencia', models.CharField(choices=[('TURMA_A', 'Turma A'), ('TURMA_B', 'Turma B')], default='TURMA_A', max_length=10, verbose_name='Turma que Trabalhou na Data de Referência')),
                ('hora_inicio', models.TimeField(default=datetime.time(6, 0), verbose_name='Horário Normal de Início (06:00)')),
                ('hora_fim', models.TimeField(default=datetime.time(18, 0), verbose_name='Horário Normal de Término (18:00)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Configuração Ativa')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Escala 12x36',
                'verbose_name_plural': 'Configurações de Escala 12x36',
            },
        ),
        migrations.CreateModel(
            name='OrdemProducaoBladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordem', models.CharField(max_length=40, unique=True, verbose_name='Número da OP')),
                ('data_programada', models.DateField(db_index=True, verbose_name='Data Programada')),
                ('turma_prevista', models.CharField(choices=[('TURMA_A', 'Turma A'), ('TURMA_B', 'Turma B')], max_length=10, verbose_name='Turma Prevista')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10, verbose_name='Prioridade')),
                ('quantidade_nova', models.PositiveIntegerField(help_text='Necessidade nova planejada pelo líder', verbose_name='Qtd Nova Solicitada')),
                ('saldo_anterior_incorporado', models.PositiveIntegerField(default=0, help_text='Saldo pendente incorporado de programações anteriores', verbose_name='Saldo Anterior Incorporado')),
                ('quantidade_planejada', models.PositiveIntegerField(help_text='Soma da Quantidade Nova com o Saldo Anterior Incorporado', verbose_name='Total Programado a Produzir')),
                ('quantidade_realizada', models.PositiveIntegerField(default=0, verbose_name='Quantidade Realizada')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_EXECUCAO', 'Em Execução'), ('CONCLUIDA', 'Concluída'), ('PARCIAL', 'Encerrada Parcial'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDENTE', max_length=20, verbose_name='Status')),
                ('recursos_observacoes', models.TextField(blank=True, null=True, verbose_name='Observações de Recursos / Instruções')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações Gerais')),
                ('motivo_cancelamento', models.TextField(blank=True, null=True, verbose_name='Motivo do Cancelamento')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora do Cancelamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_bladder_atualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_bladder_canceladas', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado por')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_bladder_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Ordem de Produção de Bladder',
                'verbose_name_plural': 'Ordens de Produção de Bladder',
                'ordering': ['data_programada', '-prioridade', 'numero_ordem'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoBladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código do Bladder')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição / Medida')),
                ('nomenclatura_antiga', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nomenclatura Antiga')),
                ('matriz_extrusao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Matriz de Extrusão')),
                ('comprimento_extrusao_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Comprimento Extrusão (cm)')),
                ('comprimento_chanfrado_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Comprimento Chanfrado (cm)')),
                ('peso_tarugo_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Peso do Tarugo (kg)')),
                ('diametro_tarugo_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Diâmetro do Tarugo (mm)')),
                ('tempo_vulcanizacao_min', models.PositiveIntegerField(blank=True, default=120, null=True, verbose_name='Tempo de Vulcanização (min)')),
                ('peso_vulcanizado_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Peso Vulcanizado (kg)')),
                ('circunferencia_centro_mm', models.CharField(blank=True, max_length=50, null=True, verbose_name='Circunferência no Centro (mm)')),
                ('altura_cm', models.CharField(blank=True, max_length=50, null=True, verbose_name='Altura (cm)')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('EM DESENVOLVIMENTO', 'Em Desenvolvimento'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=30, verbose_name='Status')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_bladder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_setor_bladder', to='production.productionbladder', verbose_name='Vínculo com Catálogo de Vulcanização (Opcional)')),
            ],
            options={
                'verbose_name': 'Produto / Modelo de Bladder',
                'verbose_name_plural': 'Produtos / Modelos de Bladder',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='RecursoBladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('MATRIZ', 'Matriz de Extrusão / Prensa'), ('COMPOSTO', 'Composto de Borracha'), ('FERRAMENTA', 'Ferramenta / Acessório'), ('MATERIA_PRIMA', 'Matéria-Prima / Tarugo'), ('OUTROS', 'Outro Recurso')], default='MATRIZ', max_length=20, verbose_name='Categoria')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Identificação')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Recurso')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição / Especificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Recurso do Setor de Bladder',
                'verbose_name_plural': 'Recursos do Setor de Bladder',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='SaldoPendenteBladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade do Saldo')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Produção'), ('INCORPORADO', 'Incorporado em Nova OP'), ('CANCELADO', 'Cancelado pela Liderança')], db_index=True, default='PENDENTE', max_length=20, verbose_name='Status do Saldo')),
                ('data_incorporacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Incorporação')),
                ('motivo_cancelamento', models.TextField(blank=True, null=True, verbose_name='Motivo de Cancelamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Geração do Saldo')),
                ('op_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saldos_incorporados', to='bladder.ordemproducaobladder', verbose_name='OP de Destino (Onde foi Incorporado)')),
                ('op_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_gerados', to='bladder.ordemproducaobladder', verbose_name='OP de Origem')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_pendentes', to='bladder.produtobladder', verbose_name='Produto / Modelo')),
            ],
            options={
                'verbose_name': 'Saldo Pendente (Ledger de Bladder)',
                'verbose_name_plural': 'Saldos Pendentes (Ledger de Bladder)',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessoBladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código do Processo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Processo')),
                ('tipo', models.CharField(choices=[('PRENSA', 'Prensa de Vulcanização'), ('EXTRUSAO', 'Extrusão'), ('ACABAMENTO', 'Acabamento / Anéis'), ('MANUAL', 'Processo Manual / Bancada'), ('OUTRO', 'Outro')], default='PRENSA', max_length=20, verbose_name='Tipo de Processo')),
                ('ordem_exibicao', models.PositiveIntegerField(default=1, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_bladder', to='maintenance.machine', verbose_name='Máquina Vinculada (Opcional)')),
            ],
            options={
                'verbose_name': 'Processo do Setor de Bladder',
                'verbose_name_plural': 'Processos do Setor de Bladder',
                'ordering': ['ordem_exibicao', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='ordemproducaobladder',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='bladder.processobladder', verbose_name='Processo'),
        ),
        migrations.AddField(
            model_name='ordemproducaobladder',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='bladder.produtobladder', verbose_name='Produto / Modelo'),
        ),
        migrations.AddField(
            model_name='ordemproducaobladder',
            name='recursos_alocados',
            field=models.ManyToManyField(blank=True, related_name='ordens', to='bladder.recursobladder', verbose_name='Recursos Necessários'),
        ),
        migrations.CreateModel(
            name='HistoricoProgramacaoBladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CRIACAO', 'Criação da OP'), ('ALTERACAO', 'Alteração de Dados'), ('REPROGRAMACAO', 'Reprogramação de Data'), ('CANCELAMENTO', 'Cancelamento da OP'), ('ENCERRAMENTO_PARCIAL', 'Encerramento Parcial de Turno'), ('CONCLUSAO', 'Conclusão da Ordem')], max_length=25, verbose_name='Tipo de Evento')),
                ('data_anterior', models.DateField(blank=True, null=True, verbose_name='Data Anterior')),
                ('data_nova', models.DateField(blank=True, null=True, verbose_name='Nova Data')),
                ('quantidade_anterior', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade Anterior')),
                ('quantidade_nova', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nova Quantidade')),
                ('motivo', models.TextField(verbose_name='Motivo / Justificativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora do Evento')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_programacao', to='bladder.ordemproducaobladder', verbose_name='Ordem de Produção')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Histórico de Programação de Bladder',
                'verbose_name_plural': 'Históricos de Programação de Bladder',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoApontamentoBladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_anterior', models.PositiveIntegerField(verbose_name='Quantidade Anterior')),
                ('quantidade_nova', models.PositiveIntegerField(verbose_name='Quantidade Corrigida')),
                ('situacao_anterior', models.CharField(blank=True, max_length=20, null=True, verbose_name='Situação Anterior')),
                ('situacao_nova', models.CharField(blank=True, max_length=20, null=True, verbose_name='Situação Corrigida')),
                ('motivo_correcao', models.TextField(verbose_name='Justificativa da Correção')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Correção')),
                ('apontamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_correcoes', to='bladder.apontamentoturnobladder', verbose_name='Apontamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Histórico de Correção de Apontamento',
                'verbose_name_plural': 'Históricos de Correções de Apontamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuncionarioApoioBladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(default='Apoio Operacional', max_length=100, verbose_name='Papel / Função de Apoio')),
                ('tipo_escala', models.CharField(choices=[('DIAS_SEMANA', 'Dias da Semana Recorrentes'), ('DATAS_ESPECIFICAS', 'Datas Específicas / Pontuais')], default='DIAS_SEMANA', max_length=20, verbose_name='Tipo de Escala')),
                ('dias_semana', models.CharField(blank=True, help_text='Números separados por vírgula (0=Segunda, 1=Terça, 2=Quarta, 3=Quinta, 4=Sexta, 5=Sábado, 6=Domingo)', max_length=30, null=True, verbose_name='Dias da Semana')),
                ('datas_especificas', models.TextField(blank=True, help_text='Uma data por linha ou separadas por vírgula', null=True, verbose_name='Datas Específicas (YYYY-MM-DD)')),
                ('hora_inicio', models.TimeField(default=datetime.time(6, 0), verbose_name='Horário de Início')),
                ('hora_fim', models.TimeField(default=datetime.time(18, 0), verbose_name='Horário de Término')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apoios_bladder', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Funcionário de Apoio Bladder',
                'verbose_name_plural': 'Funcionários de Apoio Bladder',
                'ordering': ['usuario__first_name', 'usuario__username'],
            },
        ),
        migrations.AddField(
            model_name='apontamentoturnobladder',
            name='ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to='bladder.ordemproducaobladder', verbose_name='Ordem de Produção'),
        ),
        migrations.CreateModel(
            name='AjusteEscalaExcepcionalBladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data do Ajuste')),
                ('turma_designada', models.CharField(choices=[('TURMA_A', 'Turma A'), ('TURMA_B', 'Turma B'), ('FOLGA', 'Parada Geral / Sem Produção')], max_length=10, verbose_name='Turma Designada')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo do Ajuste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Ajuste Excepcional de Escala',
                'verbose_name_plural': 'Ajustes Excepcionais de Escala',
                'ordering': ['-data'],
            },
        ),
    ]
