# Generated by Django 4.2.30 on 2026-09-29 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bladder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilOperacionalBladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(choices=[('TURMA_A', 'Turma A'), ('TURMA_B', 'Turma B')], max_length=10, verbose_name='Turma Operacional Regular')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_operacional_bladder', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil Operacional Bladder',
                'verbose_name_plural': 'Perfis Operacionais Bladder',
                'ordering': ['turma', 'usuario__first_name', 'usuario__username'],
            },
        ),
    ]
