# Generated by Django 4.2.30 on 2026-09-29 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bladder', '0002_perfiloperacionalbladder'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoTurnoBladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_turno', models.DateField(db_index=True, verbose_name='Data do Turno')),
                ('turma', models.CharField(choices=[('TURMA_A', 'Turma A'), ('TURMA_B', 'Turma B'), ('APOIO', 'Apoio Operacional')], max_length=10, verbose_name='Turma')),
                ('data_hora_fechamento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora do Fechamento')),
                ('status', models.CharField(choices=[('CONCLUIDO', 'Fechamento Concluído'), ('RETIFICADO', 'Retificado pela Liderança')], default='CONCLUIDO', max_length=20, verbose_name='Status do Fechamento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações Gerais do Turno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos_bladder', to=settings.AUTH_USER_MODEL, verbose_name='Operador Responsável pelo Fechamento')),
            ],
            options={
                'verbose_name': 'Fechamento de Turno Bladder',
                'verbose_name_plural': 'Fechamentos de Turno Bladder',
                'ordering': ['-data_turno', '-data_hora_fechamento'],
                'unique_together': {('data_turno', 'turma')},
            },
        ),
        migrations.AddField(
            model_name='apontamentoturnobladder',
            name='fechamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apontamentos_fechamento', to='bladder.fechamentoturnobladder', verbose_name='Fechamento de Origem'),
        ),
        migrations.AddField(
            model_name='saldopendentebladder',
            name='fechamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saldos_gerados_fechamento', to='bladder.fechamentoturnobladder', verbose_name='Fechamento de Origem'),
        ),
        migrations.CreateModel(
            name='ItemFechamentoTurnoBladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_programada', models.PositiveIntegerField(verbose_name='Meta Programada')),
                ('quantidade_realizada', models.PositiveIntegerField(verbose_name='Quantidade Realizada')),
                ('saldo_gerado', models.PositiveIntegerField(default=0, verbose_name='Saldo Gerado')),
                ('situacao', models.CharField(choices=[('CONCLUIDA', 'Concluída'), ('PARCIAL', 'Parcial'), ('NAO_REALIZADA', 'Não Realizada')], max_length=20, verbose_name='Situação')),
                ('motivo', models.CharField(blank=True, choices=[('PROBLEMA_EQUIPAMENTO', 'Problema de equipamento'), ('FALTA_MATERIA_PRIMA', 'Falta de matéria-prima'), ('FALTA_COMPONENTE', 'Falta de componente'), ('PROBLEMA_OPERACIONAL', 'Problema operacional'), ('ALTERACAO_PROGRAMACAO', 'Alteração de programação'), ('PROBLEMA_QUALIDADE', 'Problema de qualidade'), ('OUTRO', 'Outro')], max_length=40, null=True, verbose_name='Motivo do Saldo')),
                ('motivo_outro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Motivo (Outro)')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fechamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='bladder.fechamentoturnobladder', verbose_name='Fechamento de Turno')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_fechamento', to='bladder.ordemproducaobladder', verbose_name='Ordem de Produção')),
            ],
            options={
                'verbose_name': 'Item de Fechamento de Turno',
                'verbose_name_plural': 'Itens de Fechamento de Turno',
                'ordering': ['ordem__numero_ordem'],
                'unique_together': {('fechamento', 'ordem')},
            },
        ),
    ]
