# Generated by Django 4.2.30 on 2026-10-01 11:52

from django.db import migrations, models


def criar_categorias_iniciais(apps, schema_editor):
    Categoria = apps.get_model('bladder', 'CategoriaDesvioBladder')
    categorias = [
        ('PROBLEMA_EQUIPAMENTO', 'Problema de equipamento', 1),
        ('FALTA_MATERIA_PRIMA', 'Falta de matéria-prima', 2),
        ('PROBLEMA_QUALIDADE', 'Problema de qualidade', 3),
        ('MANUTENCAO', 'Manutenção', 4),
        ('FALTA_OPERADOR', 'Falta de operador', 5),
        ('OUTRO', 'Outro', 6),
    ]
    for codigo, nome, ordem in categorias:
        Categoria.objects.get_or_create(
            codigo=codigo,
            defaults={'nome': nome, 'ordem': ordem, 'ativo': True}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('bladder', '0003_fechamentoturnobladder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDesvioBladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True, verbose_name='Código da Categoria')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Categoria de Desvio Bladder',
                'verbose_name_plural': 'Categorias de Desvios Bladder',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='itemfechamentoturnobladder',
            name='descricao_desvio',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Ocorrido (O que aconteceu?)'),
        ),
        migrations.AlterField(
            model_name='itemfechamentoturnobladder',
            name='motivo',
            field=models.CharField(blank=True, choices=[('PROBLEMA_EQUIPAMENTO', 'Problema de equipamento'), ('FALTA_MATERIA_PRIMA', 'Falta de matéria-prima'), ('FALTA_COMPONENTE', 'Falta de componente'), ('PROBLEMA_OPERACIONAL', 'Problema operacional'), ('ALTERACAO_PROGRAMACAO', 'Alteração de programação'), ('PROBLEMA_QUALIDADE', 'Problema de qualidade'), ('MANUTENCAO', 'Manutenção'), ('FALTA_OPERADOR', 'Falta de operador'), ('OUTRO', 'Outro')], max_length=40, null=True, verbose_name='Motivo do Saldo'),
        ),
        migrations.AddField(
            model_name='itemfechamentoturnobladder',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='itens_fechamento', to='bladder.categoriadesviobladder', verbose_name='Categorias do Desvio'),
        ),
        migrations.RunPython(criar_categorias_iniciais, reverse_code=migrations.RunPython.noop),
    ]
