# Generated by Django 4.2.30 on 2026-10-05 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_ordemservico_causa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bladder', '0004_categoriadesviobladder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemPassagemTurnoBladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_turno_origem', models.DateField(db_index=True, verbose_name='Data do Turno de Origem')),
                ('turma_origem', models.CharField(choices=[('TURMA_A', 'Turma A'), ('TURMA_B', 'Turma B')], max_length=10, verbose_name='Turma de Origem')),
                ('data_turno_destino', models.DateField(db_index=True, verbose_name='Data do Turno de Destino')),
                ('turma_destino', models.CharField(choices=[('TURMA_A', 'Turma A'), ('TURMA_B', 'Turma B')], db_index=True, max_length=10, verbose_name='Turma de Destino')),
                ('tipo', models.CharField(choices=[('INFORMATIVO', 'Informativo'), ('ACOMPANHAMENTO', 'Acompanhamento')], db_index=True, default='INFORMATIVO', max_length=20, verbose_name='Tipo de Mensagem')),
                ('categoria', models.CharField(choices=[('PRODUCAO', 'Produção'), ('EQUIPAMENTO', 'Equipamento'), ('QUALIDADE', 'Qualidade'), ('MATERIAL', 'Material'), ('SEGURANCA', 'Segurança'), ('OUTRO', 'Outro')], db_index=True, default='PRODUCAO', max_length=20, verbose_name='Categoria')),
                ('prioridade', models.CharField(choices=[('NORMAL', 'Normal'), ('IMPORTANTE', 'Importante'), ('URGENTE', 'Urgente')], db_index=True, default='NORMAL', max_length=15, verbose_name='Prioridade')),
                ('mensagem', models.TextField(verbose_name='Mensagem / Recado Operacional')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('RESOLVIDA', 'Resolvida'), ('REPASSADA', 'Repassada')], db_index=True, default='ABERTA', max_length=15, verbose_name='Status')),
                ('resolvido_em', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora da Resolução')),
                ('observacao_resolucao', models.TextField(blank=True, null=True, verbose_name='Observação da Resolução')),
                ('repassado_em', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora do Repasse')),
                ('observacao_repasse', models.TextField(blank=True, null=True, verbose_name='Observação do Repasse')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensagens_turno_bladder_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Autor da Mensagem')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_turno_bladder', to='maintenance.machine', verbose_name='Máquina / Equipamento (Opcional)')),
                ('mensagem_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repasses', to='bladder.mensagempassagemturnobladder', verbose_name='Mensagem de Origem deste Repasse')),
                ('ordem_producao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_turno', to='bladder.ordemproducaobladder', verbose_name='Ordem de Produção (Opcional)')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_turno', to='bladder.processobladder', verbose_name='Processo / Linha (Opcional)')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_turno', to='bladder.produtobladder', verbose_name='Produto / Modelo (Opcional)')),
                ('repassado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_turno_bladder_repassadas', to=settings.AUTH_USER_MODEL, verbose_name='Repassado por')),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_turno_bladder_resolvidas', to=settings.AUTH_USER_MODEL, verbose_name='Resolvido por')),
            ],
            options={
                'verbose_name': 'Passagem de Turno Bladder',
                'verbose_name_plural': 'Passagens de Turno Bladder',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcaoMensagemTurnoBladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CIENTE', 'Ciente'), ('RESOLVIDO', 'Resolvido'), ('REPASSADO', 'Repassado')], db_index=True, max_length=15, verbose_name='Ação')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Ação')),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='bladder.mensagempassagemturnobladder', verbose_name='Mensagem de Turno')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes_mensagens_turno_bladder', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Ação em Mensagem de Turno',
                'verbose_name_plural': 'Ações em Mensagens de Turno',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='acaomensagemturnobladder',
            constraint=models.UniqueConstraint(fields=('mensagem', 'usuario', 'acao'), name='unique_acao_usuario_mensagem_turno'),
        ),
    ]
