# Generated by Django 4.2.27 on 2026-06-12 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do Setor"),
                ),
            ],
            options={
                "verbose_name": "Setor",
                "verbose_name_plural": "Setores",
            },
        ),
        migrations.CreateModel(
            name="Technician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do Técnico"),
                ),
                (
                    "matricula",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Matrícula"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OCIOSO", "Ocioso"),
                            ("EM_ATENDIMENTO", "Em Atendimento"),
                            ("EM_PAUSA", "Em Pausa"),
                        ],
                        default="OCIOSO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Técnico",
                "verbose_name_plural": "Técnicos",
            },
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome da Máquina"),
                ),
                (
                    "criticidade",
                    models.CharField(
                        choices=[
                            ("BAIXA", "Baixa (Verde)"),
                            ("MEDIA", "Média (Amarela)"),
                            ("ALTA", "Alta (Vermelha)"),
                        ],
                        default="BAIXA",
                        max_length=10,
                        verbose_name="Criticidade",
                    ),
                ),
                (
                    "setor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maquinas",
                        to="maintenance.sector",
                        verbose_name="Setor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Máquina",
                "verbose_name_plural": "Máquinas",
            },
        ),
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "atividade_observacao",
                    models.TextField(verbose_name="Atividade/Observação"),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(verbose_name="Data/Hora de Início"),
                ),
                (
                    "data_pausa",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data/Hora de Pausa"
                    ),
                ),
                (
                    "motivo_pausa",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motivo da Pausa"
                    ),
                ),
                (
                    "data_fim",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data/Hora de Fim"
                    ),
                ),
                (
                    "observacao_conclusao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observação de Conclusão"
                    ),
                ),
                (
                    "foto_anexo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="alocacoes/",
                        verbose_name="Foto/Anexo",
                    ),
                ),
                (
                    "maquina",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allocations",
                        to="maintenance.machine",
                        verbose_name="Máquina",
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="maintenance.technician",
                        verbose_name="Técnico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alocação",
                "verbose_name_plural": "Alocações",
            },
        ),
    ]
