# Generated by Django 4.2.30 on 2026-06-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="status",
            field=models.CharField(
                choices=[
                    ("EM_ATENDIMENTO", "Em Atendimento"),
                    ("EM_PAUSA", "Em Pausa"),
                ],
                default="EM_ATENDIMENTO",
                max_length=20,
                verbose_name="Status da Alocação",
            ),
        ),
    ]
