# Generated by Django 4.2.30 on 2026-06-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0002_allocation_add_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technician",
            name="status",
            field=models.CharField(
                choices=[
                    ("OCIOSO", "Disponível (Ocioso)"),
                    ("EM_ATENDIMENTO", "Em Atendimento"),
                    ("EM_PAUSA", "Em Pausa"),
                    ("AUSENTE_FOLGA", "Ausente – Folga/Escala"),
                    ("AUSENTE_FERIAS", "Ausente – Férias"),
                    ("AUSENTE_MEDICO", "Ausente – Licença Médica/Afastamento"),
                    ("EXTERNO_PLANTAO", "Plantão Fora da Fábrica"),
                ],
                default="OCIOSO",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
