# Generated by Django 4.2.27 on 2026-06-16 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0003_technician_expand_status_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoPausa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_pausa", models.DateTimeField(verbose_name="Data/Hora de Pausa")),
                (
                    "data_retorno",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data/Hora de Retorno"
                    ),
                ),
                ("motivo_pausa", models.TextField(verbose_name="Motivo da Pausa")),
                (
                    "alocacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pausas",
                        to="maintenance.allocation",
                        verbose_name="Alocação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Pausa",
                "verbose_name_plural": "Histórico de Pausas",
                "ordering": ["data_pausa"],
            },
        ),
    ]
