# Generated by Django 4.2.27 on 2026-06-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0004_historicopausa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allocation",
            name="status",
            field=models.CharField(
                choices=[
                    ("EM_ATENDIMENTO", "Em Atendimento"),
                    ("EM_PAUSA", "Em Pausa"),
                    ("CONCLUIDO", "Concluído"),
                ],
                default="EM_ATENDIMENTO",
                max_length=20,
                verbose_name="Status da Alocação",
            ),
        ),
    ]
