# Generated by Django 4.2.30 on 2026-06-16 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maintenance", "0005_alter_allocation_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoEscala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_definido",
                    models.CharField(max_length=20, verbose_name="Status Definido"),
                ),
                (
                    "data_alteracao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data/Hora da Alteração"
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_escalas",
                        to="maintenance.technician",
                        verbose_name="Técnico",
                    ),
                ),
                (
                    "usuario_responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Escala",
                "verbose_name_plural": "Histórico de Escalas",
                "ordering": ["-data_alteracao"],
            },
        ),
    ]
