# Generated by Django 4.2.30 on 2026-06-16 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maintenance", "0006_historico_escala"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="usuario_operador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Operador Responsável",
            ),
        ),
    ]
