# Generated by Django 4.2.30 on 2026-06-17 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maintenance", "0007_usuario_operador_alocacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="technician",
            name="perfil",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TECNICO", "Técnico (Acesso apenas ao próprio card)"),
                    ("OPERADOR", "Operador/Líder (Acesso total)"),
                ],
                default="TECNICO",
                max_length=10,
                null=True,
                verbose_name="Perfil de Acesso",
            ),
        ),
        migrations.AddField(
            model_name="technician",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="technician_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário do Sistema",
            ),
        ),
    ]
