# Generated by Django 4.2.30 on 2026-06-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0008_technician_user_perfil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technician",
            name="perfil",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TECNICO", "Técnico (Acesso apenas ao próprio card)"),
                    (
                        "TECNICO_LIDER",
                        "Técnico Líder (Acesso ao painel e dashboard — sem cadastros)",
                    ),
                    (
                        "OPERADOR",
                        "Operador/Administrador (Acesso total incluindo cadastros)",
                    ),
                ],
                default="TECNICO",
                max_length=15,
                null=True,
                verbose_name="Perfil de Acesso",
            ),
        ),
    ]
