# Generated by Django 4.2.30 on 2026-06-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0009_perfil_max_length_tecnico_lider"),
    ]

    operations = [
        migrations.AddField(
            model_name="technician",
            name="whatsapp",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="WhatsApp"
            ),
        ),
    ]
