# Generated by Django 4.2.30 on 2026-06-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0010_technician_whatsapp"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do Grupo"),
                ),
                (
                    "jid",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="JID do Grupo"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Grupo de WhatsApp",
                "verbose_name_plural": "Grupos de WhatsApp",
            },
        ),
    ]
