# Generated by Django 4.2.30 on 2026-08-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_whatsappgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo no quadro da empresa'),
        ),
        migrations.AlterField(
            model_name='historicoescala',
            name='status_definido',
            field=models.CharField(max_length=30, verbose_name='Status Definido'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='status',
            field=models.CharField(choices=[('OCIOSO', 'Disponível (Ocioso)'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('EM_PAUSA', 'Em Pausa'), ('AUSENTE_FOLGA', 'Ausente – Folga/Escala'), ('AUSENTE_FERIAS', 'Ausente – Férias'), ('AUSENTE_MEDICO', 'Ausente – Licença Médica/Afastamento'), ('EXTERNO_PLANTAO', 'Plantão Fora da Fábrica'), ('AUSENTE_FALTA_JUSTIFICADA', 'Ausente – Falta Justificada'), ('AUSENTE_FALTA_NAO_JUSTIFICADA', 'Ausente – Falta Não Justificada')], default='OCIOSO', max_length=30, verbose_name='Status'),
        ),
    ]
