# Generated by Django 4.2.30 on 2026-08-04 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0012_technician_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição da Atualização')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='maintenance.allocation', verbose_name='Alocação')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor da Atualização')),
            ],
            options={
                'verbose_name': 'Atualização de Progresso',
                'verbose_name_plural': 'Atualizações de Progresso',
                'ordering': ['criado_em'],
            },
        ),
    ]
