# Generated by Django 4.2.30 on 2026-08-20 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0013_allocationprogressupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_os', models.CharField(help_text='Número impresso na folha física. Deve ser único para evitar duplicidades.', max_length=50, unique=True, verbose_name='Número da OS Física')),
                ('solicitante', models.CharField(max_length=120, verbose_name='Solicitante / Líder de Produção')),
                ('tipo_manutencao', models.CharField(choices=[('CORRETIVA', 'Corretiva'), ('PREVENTIVA', 'Preventiva'), ('PREDITIVA', 'Preditiva'), ('MELHORIA', 'Melhoria / Instalação'), ('OUTRO', 'Outro')], default='CORRETIVA', max_length=20, verbose_name='Tipo de Manutenção')),
                ('criticidade', models.CharField(choices=[('BAIXA', 'Baixa (Normal)'), ('MEDIA', 'Média'), ('ALTA', 'Alta (Urgente / Parada de Máquina)')], default='MEDIA', max_length=15, verbose_name='Criticidade')),
                ('descricao_falha', models.TextField(verbose_name='Descrição do Defeito / Solicitação')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente (Aguardando Atendimento)'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='Status da OS')),
                ('foto_abertura', models.ImageField(blank=True, null=True, upload_to='ordens_servico/abertura/%Y/%m/', verbose_name='Foto da OS na Abertura')),
                ('foto_conclusao', models.ImageField(blank=True, null=True, upload_to='ordens_servico/conclusao/%Y/%m/', verbose_name='Foto da OS Finalizada e Assinada')),
                ('data_abertura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora de Abertura')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Conclusão')),
                ('observacao_fechamento', models.TextField(blank=True, null=True, verbose_name='Observações de Fechamento / Ação Executada')),
                ('lider_assinatura_nome', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nome do Líder que Assinou a Conclusão')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_abertas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Cadastrou')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='maintenance.machine', verbose_name='Máquina')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='maintenance.sector', verbose_name='Setor')),
                ('tecnico_designado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_designadas', to='maintenance.technician', verbose_name='Técnico Designado (Opcional)')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.AddField(
            model_name='allocation',
            name='ordem_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='maintenance.ordemservico', verbose_name='Ordem de Serviço Vinculada'),
        ),
    ]
