# Generated by Django 4.2.30 on 2026-08-20 11:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_ordemservico_allocation_ordem_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='causa',
            field=models.TextField(blank=True, null=True, verbose_name='Causa da Falha (Conferir no Verso)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_hora_fim_conserto',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim do Conserto'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_hora_fim_ocorrencia',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim da Ocorrência (Máquina Liberada)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_hora_inicio_conserto',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início do Conserto'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_hora_inicio_ocorrencia',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início da Ocorrência'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='descricao_equipamento',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descrição do Equipamento'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='descricao_servico_realizado',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Serviço Realizado'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='foto_verso',
            field=models.ImageField(blank=True, null=True, upload_to='ordens_servico/verso/%Y/%m/', verbose_name='Foto do Verso da OS (Opcional)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='motivo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo do Chamado'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='parou_maquina',
            field=models.BooleanField(default=True, verbose_name='Parou a Máquina?'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TAG do Equipamento'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='visto_executante_data',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Visto Executante'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='visto_executante_nome',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Visto Executante (Nome do Técnico)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='visto_responsavel_data',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Visto Responsável'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='visto_responsavel_nome',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Visto Responsável (Nome do Líder)'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='data_abertura',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora de Cadastro no Sistema'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Conclusão no Sistema'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='descricao_falha',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Serviço a ser Realizado'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='maintenance.machine', verbose_name='Máquina Relacionada'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='numero_os',
            field=models.CharField(help_text='Número impresso na folha física (ex: 10216). Deve ser único para evitar duplicidades.', max_length=50, unique=True, verbose_name='Número da OS Física'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='solicitante',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Solicitante / Líder de Produção'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tecnico_designado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_designadas', to='maintenance.technician', verbose_name='Técnico Designado Principal (Opcional)'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo_manutencao',
            field=models.CharField(choices=[('CORRETIVA', 'Corretiva'), ('PREVENTIVA', 'Preventiva'), ('MELHORIA', 'Melhoria'), ('PREDIAL', 'Predial'), ('OUTRO', 'Outro')], default='CORRETIVA', max_length=20, verbose_name='Tipo de Serviço'),
        ),
        migrations.CreateModel(
            name='OrdemServicoPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código da Peça')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição da Peça / Material')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Quantidade')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_utilizadas', to='maintenance.ordemservico', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Peça Utilizada',
                'verbose_name_plural': 'Peças Utilizadas',
            },
        ),
    ]
